### ISSUE TITLE
Update actions/checkout to v4 in generated project

### ISSUE THREAD

**Issue by jeckel** [Jeckel-Lab/cookiecutter-php#2]
```yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
```

See dependapot PR https://github.com/Jeckel-Lab/etl/pull/1
